comoContratar&comoFunciona_Diego_Denis_Cristian
foobardual/Foobardual pull request #2
Opened 2017-02-14 16:39 UTC by DiegoVivanco

2017-02-14 16:44 UTC, aamerino commented
Tenéis que añadir los archivos en la carpeta /pages.

Es importante mantener la estructura del proyecto.

Gracias

2017-02-14 17:00 UTC, RicardoGarrido commented
Pensad que las primeras letras de los elementos HTML h las controlaremos desde CSS no hace falta que este en mayusculas

2017-02-14 17:02 UTC, aamerino requested changes
Tenéis que añadir los archivos en la carpeta /pages.

Es importante mantener la estructura del proyecto.

Gracias

2017-02-14 17:05 UTC, RicardoGarrido requested changes

2017-02-14 17:05 UTC, RicardoGarrido commented on como_contratar.html
> +<html lang="en">
lang tendria que estar en la lengua apropiada

2017-02-14 17:05 UTC, RicardoGarrido commented on como_contratar.html
> +<div id="container">
De este punto no estoy seguro, pero creo recordar que definimos container como una clase

2017-02-14 17:05 UTC, RicardoGarrido commented on como_contratar.html
> +    <link rel="stylesheet" type="text/css" href="como_contratar.css" />
si no habéis creado un fichero css no lo llaméis

2017-02-14 17:05 UTC, RicardoGarrido commented on como_contratar.html
> +    <h1>¿Cómo contratar?</h1>
Las primeras letras de los elementos h dejadlas en minúsculas, se tiene que controlar desde el css

2017-02-14 17:08 UTC, Kazanhel commented on como_contratar.html
> +<div id="container">
Creo que cuando lo hablamos ayer acordamos que sería un id. Que alguien nos saque de dudas!

2017-02-16 07:59 UTC, aamerino commented on como_contratar.html
> +<div id="container">
Si solo hay uno por pagina, me parece mas correcto que sea un id. Aver que dicen los expertos del front.

2017-02-20 15:12 UTC, merged