prototipo experiencias
foobardual/Foobardual pull request #3
Opened 2017-02-14 16:49 UTC by RdelaCruzMartinez

2017-02-14 17:00 UTC, aamerino requested changes

2017-02-14 17:00 UTC, aamerino commented on pages/experiencias.html
> +    <div id="container">
El container tiene que contener todo.

2017-02-14 17:00 UTC, aamerino commented on pages/experiencias.html
> +</html>
salto de linea al final

2017-02-14 17:00 UTC, aamerino commented on pages/experiencias.html
> +
Hay que determinar como equipo si vamos a usar la etiqueta lang.
> lang="es">

2017-02-14 17:01 UTC, RicardoGarrido requested changes

2017-02-14 17:01 UTC, RicardoGarrido commented on pages/experiencias.html
> +            <h2>profesores</h2>
habrá una única historia que abarcara la de todos los profesores? o sera una sección que contendrá múltiples historias?

2017-02-16 08:03 UTC, aamerino approved these changes

2017-02-20 16:16 UTC, merged

2017-02-20 16:22 UTC, RicardoGarrido commented on pages/experiencias.html
> +            <h2>profesores</h2>
para que se entienda mejor a lo que me refiero, si la sección contiene varias historias de profesores, interesaría cerrar cada agrupación de "cual es su historia" y "que opinan de los alumnos" en un div, para que estructuralmente quede claro que cada div es una historia diferente.