commiteando estructura home
foobardual/Foobardual pull request #4
Opened 2017-02-20 15:14 UTC by mgustran

2017-02-20 15:28 UTC, aamerino approved these changes

2017-02-20 15:49 UTC, dcarril reviewed
Añadir nuevas líneas al final de los documentos.

2017-02-20 16:29 UTC, Maximoguitar commented on pages/home.html
> +<div id="container">
el container es una clase

2017-02-20 16:38 UTC, RicardoGarrido requested changes
Creo que el resumen tendría que estar en una sección y no en un div, hay una id="resumen" y justo el elemento hijo tiene un id="contenido" creo que se puede mejorar. Por lo demás lo veo todo bien!

2017-02-21 16:03 UTC, RdelaCruzMartinez commented on pages/home.html
> +</html>
falta añadir una linea al final

2017-02-21 16:04 UTC, RdelaCruzMartinez commented on pages/quieres_contratar.html
> +</html>
linea

2017-02-21 16:05 UTC, RdelaCruzMartinez commented on pages/quieres_estudiar.html
> +</html>
aquí también, falta añadir una nueva linea

2017-02-21 16:12 UTC, dcarril approved these changes

2017-02-21 16:44 UTC, Kazanhel reviewed
Dejad una línea en blanco al final de cada archivo.

2017-02-21 16:44 UTC, Kazanhel commented on pages/quieres_estudiar.html
> +</html>
dejad una línea en blanco al final de cada archivo

2017-02-28 15:41 UTC, Ruvikx commented
Creo que en principio no había que crear estilos más que para "display" y "width(%)".

2017-03-06 00:37 UTC, merged