Adding Id's to sections
foobardual/Foobardual pull request #5
Opened 2017-02-20 15:29 UTC by aamerino

2017-02-20 15:31 UTC, dcarril approved these changes

2017-02-20 16:27 UTC, Maximoguitar commented on pages/que_perfiles_ofrecemos.html
>              <li><h3>Programación:</h3>
Programación con p minúscula

2017-02-21 15:45 UTC, Globix approved these changes

2017-02-21 16:01 UTC, RdelaCruzMartinez commented on pages/header.html
> +        <h1>Seccion titulo</h1>
no debería haber mayúsculas fuera del title

2017-02-21 16:01 UTC, RdelaCruzMartinez commented on pages/menu.html
> +        <li><a href="index.html#quieres_contratar">¿Quieres trabajar?</a>
mayúsculas

2017-02-21 16:02 UTC, RdelaCruzMartinez requested changes
revisar mayúsculas

2017-02-21 16:52 UTC, merged