Añadidas ids a las etiquetas section
foobardual/Foobardual pull request #6
Opened 2017-02-20 15:34 UTC by crisjsg

2017-02-20 15:46 UTC, dcarril approved these changes

2017-02-20 15:46 UTC, TronHo commented on pages/como_funciona.html
>  </html>
Añadir nueva línea al final del documento.

2017-02-20 15:46 UTC, TronHo commented on pages/como_contratar.html
>  </html>
Añadir nueva línea al final del documento.

2017-02-20 15:46 UTC, TronHo commented on pages/como_contratar.html
> +            <h1>¿Cómo contratar?</h1>
*TODOS* los títulos (h1, h2, h3) han de empezar en minúscula. Nos encargaremos mediante CSS para las mayúsculas

2017-02-20 15:47 UTC, dcarril approved these changes

2017-02-20 16:20 UTC, Maximoguitar commented on pages/como_contratar.html
> -    <h1>¿Cómo contratar?</h1>
las etiquetas h (h1, h2...) tienen que estar en minúsculas.

2017-02-20 16:29 UTC, RicardoGarrido approved these changes
por mi ok

2017-02-20 16:42 UTC, RdelaCruzMartinez requested changes
el archivo no debe contener mayúsculas aparte de en el title

2017-02-21 15:02 UTC, aamerino approved these changes

2017-02-21 15:45 UTC, RdelaCruzMartinez approved these changes

2017-02-21 15:51 UTC, Globix commented on pages/como_contratar.html
> +                <h2>suía paso a paso</h2>
Se os ha colado una 's'

2017-02-21 15:54 UTC, Globix commented on pages/como_funciona.html
> +                <h2>Módulos</h2>
Falta este h2 por bajar la mayúscula

2017-02-21 15:54 UTC, Globix approved these changes

2017-02-21 15:59 UTC, GarciaExpositoVictor commented on pages/como_contratar.html
> +                <h2>suía paso a paso</h2>
no es suía, es guía

2017-02-21 15:59 UTC, GarciaExpositoVictor commented on pages/como_funciona.html
> +                <h2>Módulos</h2>
Módulos con m minúscula

2017-02-28 15:38 UTC, Ruvikx approved these changes

2017-02-28 15:38 UTC, Ruvikx commented on pages/como_contratar.html
> +        <div id="container">
El container debería estar en una clase.

2017-02-28 15:38 UTC, Ruvikx commented on pages/como_contratar.html
>  </html>
Añadir línea vacía.

2017-02-28 15:38 UTC, Ruvikx commented on pages/como_funciona.html
> +        <div id="container">
class en vez de id

2017-02-28 15:38 UTC, Ruvikx commented on pages/como_funciona.html
> +                <h2>Módulos</h2>
+1

2017-02-28 15:38 UTC, Ruvikx commented on pages/como_funciona.html
>  </html>
Añadir línea vacía.

2017-03-06 15:21 UTC, merged