Primera iteracion historias usuario 8 y 16
foobardual/Foobardual pull request #7
Opened 2017-02-20 15:40 UTC by Ruvikx

2017-02-20 16:33 UTC, dcarril requested changes
Añadid nueva línea al final de los documentos

2017-02-20 16:34 UTC, RdelaCruzMartinez reviewed
No había que crear estilos todavía.

2017-02-21 15:42 UTC, RdelaCruzMartinez commented on pages/donde_trabajaras.html
> +            <section>
os faltaría ponerles id a las secciones

2017-02-21 15:53 UTC, dcarril approved these changes

2017-02-21 16:15 UTC, Globix requested changes

2017-02-21 16:15 UTC, Globix commented on index.html
>  </html>
No entiendo porque en el index.html está esta información. ¿Se han mezclado mal los ficheros?

2017-02-21 16:18 UTC, Kazanhel commented on index.html
> +<html lang="en">
Habría que ponerlo en Español:
<html lang ="es">

2017-02-21 16:18 UTC, Kazanhel commented on pages/donde_trabajaras.html
> +<html lang="en">
<html lang="es">

2017-02-21 16:18 UTC, Kazanhel commented on pages/donde_trabajaras.html
> +<html lang="en">
<html lang ="es">

2017-02-21 16:21 UTC, Kazanhel approved these changes

2017-03-06 15:23 UTC, Globix approved these changes

2017-03-06 16:07 UTC, merged